## Q1 Perceptron 
This exercise requires the student to understand the basics of linear classification using perceptron update rule. To start any machine learning task, it requires data exploration and data cleaning. We will be using a real-life dataset from NBA which includes details about rookie basketball players such as games played, points per game, rebounds, assists and blocks to predict if the player will be in NBA after 5 years. To get more details about the dataset, please explore the link provided below

https://data.world/exercises/logistic-regression-exercise-1

### Reading the data
To start of, we will be making use of pandas library to read and do brief data cleaning. We will be using the nba_data_train.csv to train our model and this model will be tested for its performance using the nba_data_test.csv file. 

In [1]:
import pandas as pd

In [2]:
#Reading "nba_data_train.csv" into variable "df" [2 points]
df = pd.read_csv("nba_data_train.csv")
df

Name  GP   MIN  PTS  FGM  FGA   FG%  3P Made  3PA   3P%  ...  \
0     Brandon Ingram  36  27.4  7.4  2.6  7.6  34.7      0.5  2.1  25.0  ...   
1    Andrew Harrison  35  26.9  7.2  2.0  6.7  29.6      0.7  2.8  23.5  ...   
2     JaKarr Sampson  74  15.3  5.2  2.0  4.7  42.2      0.4  1.7  24.4  ...   
3        Malik Sealy  58  11.6  5.7  2.3  5.5  42.6      0.1  0.5  22.6  ...   
4        Matt Geiger  48  11.5  4.5  1.6  3.0  52.4      0.0  0.1   0.0  ...   
..               ...  ..   ...  ...  ...  ...   ...      ...  ...   ...  ...   
995   Jamaal Tinsley  80  30.5  9.4  3.6  9.5  38.0      0.5  2.2  24.0  ...   
996     Sonny Parker  77  29.4  9.2  3.5  8.3  41.9      0.8  2.5  32.3  ...   
997  Trenton Hassell  78  28.7  8.7  3.4  8.1  42.5      0.8  2.1  36.4  ...   
998  Justin Anderson  55  11.8  3.8  1.3  3.2  40.6      0.4  1.5  26.5  ...   
999    Eddie Griffin  73  26.0  8.8  3.3  9.1  36.6      1.2  3.7  33.0  ...   

     FTA   FT%  OREB  DREB  REB  AST  STL  BLK  TOV  TARGET_5Yrs  
0    2.3  69.9   0.7   3.4  4.1  1.9  0.4  0.4  1.3           -1  
1    3.4  76.5   0.5   2.0  2.4  3.7  1.1  0.5  1.6           -1  
2    1.3  67.0   0.5   1.7  2.2  1.0  0.5  0.3  1.0           -1  
3    1.3  68.9   1.0   0.9  1.9  0.8  0.6  0.1  1.0            1  
4    1.9  67.4   1.0   1.5  2.5  0.3  0.3  0.4  0.8            1  
..   ...   ...   ...   ...  ...  ...  ...  ...  ...          ...  
995  2.3  70.4   1.0   2.8  3.7  8.1  1.7  0.5  3.4            1  
996  2.1  67.5   0.4   2.1  2.6  4.3  1.2  0.1  2.0            1  
997  1.5  76.3   0.8   2.4  3.3  2.2  0.7  0.6  1.3            1  
998  1.0  80.0   0.3   2.1  2.4  0.5  0.3  0.5  0.4           -1  
999  1.2  74.4   1.6   4.1  5.7  0.7  0.2  1.8  0.6            1  

[1000 rows x 21 columns]

From the above code block, we can see the number of rows and columns in the given dataset. To see the values for each column for our first row, please run the code block given below

In [3]:
df.iloc[0]

Name           Brandon Ingram
GP                         36
MIN                      27.4
PTS                       7.4
FGM                       2.6
FGA                       7.6
FG%                      34.7
3P Made                   0.5
3PA                       2.1
3P%                      25.0
FTM                       1.6
FTA                       2.3
FT%                      69.9
OREB                      0.7
DREB                      3.4
REB                       4.1
AST                       1.9
STL                       0.4
BLK                       0.4
TOV                       1.3
TARGET_5Yrs                -1
Name: 0, dtype: object

As you can observe, almost all the features are numbers except the name of the player. However, we are not sure if our dataset has any missing values. To tackle this problem, we could either remove the null valued row or column or replace the value with either median value or a user defined value. For our dataset, make use of an in-built function in pandas to remove all the null values.

In [4]:
#Remove all the null values using a built-in function [2 points]
df = df.dropna()
df

Name  GP   MIN  PTS  FGM  FGA   FG%  3P Made  3PA   3P%  ...  \
0     Brandon Ingram  36  27.4  7.4  2.6  7.6  34.7      0.5  2.1  25.0  ...   
1    Andrew Harrison  35  26.9  7.2  2.0  6.7  29.6      0.7  2.8  23.5  ...   
2     JaKarr Sampson  74  15.3  5.2  2.0  4.7  42.2      0.4  1.7  24.4  ...   
3        Malik Sealy  58  11.6  5.7  2.3  5.5  42.6      0.1  0.5  22.6  ...   
4        Matt Geiger  48  11.5  4.5  1.6  3.0  52.4      0.0  0.1   0.0  ...   
..               ...  ..   ...  ...  ...  ...   ...      ...  ...   ...  ...   
995   Jamaal Tinsley  80  30.5  9.4  3.6  9.5  38.0      0.5  2.2  24.0  ...   
996     Sonny Parker  77  29.4  9.2  3.5  8.3  41.9      0.8  2.5  32.3  ...   
997  Trenton Hassell  78  28.7  8.7  3.4  8.1  42.5      0.8  2.1  36.4  ...   
998  Justin Anderson  55  11.8  3.8  1.3  3.2  40.6      0.4  1.5  26.5  ...   
999    Eddie Griffin  73  26.0  8.8  3.3  9.1  36.6      1.2  3.7  33.0  ...   

     FTA   FT%  OREB  DREB  REB  AST  STL  BLK  TOV  TARGET_5Yrs  
0    2.3  69.9   0.7   3.4  4.1  1.9  0.4  0.4  1.3           -1  
1    3.4  76.5   0.5   2.0  2.4  3.7  1.1  0.5  1.6           -1  
2    1.3  67.0   0.5   1.7  2.2  1.0  0.5  0.3  1.0           -1  
3    1.3  68.9   1.0   0.9  1.9  0.8  0.6  0.1  1.0            1  
4    1.9  67.4   1.0   1.5  2.5  0.3  0.3  0.4  0.8            1  
..   ...   ...   ...   ...  ...  ...  ...  ...  ...          ...  
995  2.3  70.4   1.0   2.8  3.7  8.1  1.7  0.5  3.4            1  
996  2.1  67.5   0.4   2.1  2.6  4.3  1.2  0.1  2.0            1  
997  1.5  76.3   0.8   2.4  3.3  2.2  0.7  0.6  1.3            1  
998  1.0  80.0   0.3   2.1  2.4  0.5  0.3  0.5  0.4           -1  
999  1.2  74.4   1.6   4.1  5.7  0.7  0.2  1.8  0.6            1  

[989 rows x 21 columns]

After removing all the null values from the dataset, we can separate the columns into features which are used as an input for our model and target which is the predicted value by our model. (hint: remember to remove "Name" column for your feature vectors)

In [5]:
train_target = df['TARGET_5Yrs'].to_numpy()
train_features = df.drop(['Name','TARGET_5Yrs'], axis = 1).to_numpy()
print("Shape of target : ", train_target.shape)
print("Shape of features : ", train_features.shape)
train_features

Shape of target :  (989,)
Shape of features :  (989, 19)


array([[36. , 27.4,  7.4, ...,  0.4,  0.4,  1.3],
       [35. , 26.9,  7.2, ...,  1.1,  0.5,  1.6],
       [74. , 15.3,  5.2, ...,  0.5,  0.3,  1. ],
       ...,
       [78. , 28.7,  8.7, ...,  0.7,  0.6,  1.3],
       [55. , 11.8,  3.8, ...,  0.3,  0.5,  0.4],
       [73. , 26. ,  8.8, ...,  0.2,  1.8,  0.6]])

### Todo: Fill up the functions given below to implement a linear classifier with perceptron update rule. It is encouraged to make use of numpy library as it is computationally efficient

In [6]:
import numpy as np
import random 

In [7]:
#Through this function, you need to define initial values (which are all 0) of our theta vector and offset.
#"n" is the number of dimensions for feature vectors.
#This question worth [3 points]
def init_params_with_zeroes(n): 
    ### TODO ##
    theta = np.array([0.0]*n)
    offset = 0.0
    return theta, offset
    ###########

In [8]:
init_params_with_zeroes(19)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]),
 0.0)

In [9]:
#Through this function, you need to define initial values (which are all 1) of our theta vector and offset.
#"n" is the number of dimensions for feature vectors.
#This question worth [3 points]
def init_params_with_ones(n):
    ### TODO ##
    theta = np.array([1.0]*n)
    offset = 1.0
    return theta, offset
    ###########

In [10]:
init_params_with_ones(19)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]),
 1.0)

In [11]:
#Through this function, you need to define initial values (which are all random values) of our theta vector and offset.
#"n" is the number of dimensions for feature vectors.
#This question worth [3 points]
def init_params_with_random(n): 
    ### TODO ##
    theta = np.array([random.Random(1).random() for i in range(n)])
    offset = random.Random(1).random()
    return theta, offset
    ###########

In [12]:
init_params_with_random(19)

(array([0.13436424, 0.13436424, 0.13436424, 0.13436424, 0.13436424,
        0.13436424, 0.13436424, 0.13436424, 0.13436424, 0.13436424,
        0.13436424, 0.13436424, 0.13436424, 0.13436424, 0.13436424,
        0.13436424, 0.13436424, 0.13436424, 0.13436424]),
 0.13436424411240122)

In [13]:
#Through this function, you need to write from scratch of a perceptron training algorithms without offset.
#for the input: "theta" is the initial theta vector, "xs" is our feature vectors from the training dataset.
#"ys" is the output vector (the vector of "labels"), "epochs" is the number of times your "perceptron algorithm" run through the whole training dataset.
#This question worth [6 points]

def train_perceptron_without_offset(theta, xs, ys, epochs): 
    ### TODO ##
    while epochs>0:
        for i,j in zip(xs, ys):
            if j*(np.dot(i, theta))<=0:
                theta += i*j
        epochs-=1
            
    return theta
    ###########

In [14]:
#Through this function, you need to write from scratch of a perceptron training algorithms with offset.
#for the input: "theta" is the initial theta vector, "offset" is the initial offset velue, "xs" is our feature vectors from the training dataset.
#"ys" is the output vector (the vector of "labels"), "epochs" is the number of times your "perceptron algorithm" run through the whole training dataset.
#This question worth [6 points]

def train_perceptron_with_offset(theta, offset, xs, ys, epochs):
    ### TODO ##
    while epochs>0:
        for i,j in zip(xs, ys):
            if j*(np.dot(i, theta) + offset)<=0:
                theta += i*j
                offset += j
        epochs-=1
            
    return theta, offset
    ###########

In [15]:
def test_perceptron(theta, offset, xs, ys):
    test_count = len(xs)
    # The below line is a vectorized way of checking if y(θx+θo) > 0 for all x and y
    results = ys * (xs.dot(theta) + offset) > 0.0  # returns True/False array
    correct = results.sum()
    return correct / test_count, correct, test_count

In [16]:
df = pd.read_csv("nba_data_test.csv")
test_target = df['TARGET_5Yrs'].to_numpy()
test_features = df.drop(['Name','TARGET_5Yrs'], axis = 1).to_numpy()

### a) With zeroes as initial parameters over 1 epoch and no offset

In [17]:
theta, offset = init_params_with_zeroes(len(train_features[0]))
theta = train_perceptron_without_offset(theta, train_features, train_target,1)
acc, correct, test_count = test_perceptron(theta, 0, test_features, test_target)
print(f'Results after 5 epochs:\n'
      f'Theta {theta}\n'
      f'Test accuracy {acc*100}% ({correct} of {test_count})\n')

Results after 5 epochs:
Theta [172.   76.7 145.2  53.6  83.1 -40.4   0.5  -9.6  34.5  36.2  40.  -44.
  25.7  30.4  57.1   7.9   4.    3.1  16.3]
Test accuracy 67.3529411764706% (229 of 340)



### b) With zeroes as initial parameters over 1 epoch with offset

In [18]:
theta, offset = init_params_with_zeroes(len(train_features[0]))
theta, offset = train_perceptron_with_offset(theta, offset, train_features, train_target,1)
acc, correct, test_count = test_perceptron(theta, offset, test_features, test_target)
print(f'Results after 5 epochs:\n'
      f'Theta {theta}\nOffset {offset}\n'
      f'Test accuracy {acc*100}% ({correct} of {test_count})\n')

Results after 5 epochs:
Theta [172.   76.7 145.2  53.6  83.1 -40.4   0.5  -9.6  34.5  36.2  40.  -44.
  25.7  30.4  57.1   7.9   4.    3.1  16.3]
Offset -8.0
Test accuracy 67.3529411764706% (229 of 340)



### c) With zeroes as initial parameters over 5 epochs with offset

In [19]:
theta, offset = init_params_with_zeroes(len(train_features[0]))
theta, offset = train_perceptron_with_offset(theta, offset, train_features, train_target,5)
acc, correct, test_count = test_perceptron(theta, offset, test_features, test_target)
print(f'Results after 5 epochs:\n'
      f'Theta {theta}\nOffset {offset}\n'
      f'Test accuracy {acc*100}% ({correct} of {test_count})\n')

Results after 5 epochs:
Theta [ 250.  -118.2  372.7  124.6  125.6  -56.9   -9.9  -73.6   -9.5  127.9
  132.4 -100.4   80.4    7.2   92.   -15.7   13.7   -3.1   27.4]
Offset -36.0
Test accuracy 68.82352941176471% (234 of 340)



### d) With ones as initial parameters over 5 epochs with offset

In [20]:
theta, offset = init_params_with_ones(len(train_features[0]))
theta, offset = train_perceptron_with_offset(theta, offset, train_features, train_target, 5)
acc, correct, test_count = test_perceptron(theta, offset, test_features, test_target)
print(f'Results after 5 epochs:\n'
      f'Theta {theta}\nOffset {offset}\n'
      f'Test accuracy {acc*100}% ({correct} of {test_count})\n')

Results after 5 epochs:
Theta [ 200.  -136.4  375.9  127.6  124.3  -32.9  -16.7  -99.2   43.3  136.
  140.5  -47.4   90.5   19.5  112.4  -10.7   10.3   -1.2   26.8]
Offset -35.0
Test accuracy 67.3529411764706% (229 of 340)



### e) With random as initial parameters over 5 epochs with offset

In [21]:
theta, offset = init_params_with_random(len(train_features[0]))
theta, offset = train_perceptron_with_offset(theta, offset, train_features, train_target, 5)
acc, correct, test_count = test_perceptron(theta, offset, test_features, test_target)
print(f'Results after 5 epochs:\n'
      f'Theta {theta}\nOffset {offset}\n'
      f'Test accuracy {acc*100}% ({correct} of {test_count})\n')

Results after 5 epochs:
Theta [ 175.13436424 -127.96563576  396.43436424  135.03436424  138.83436424
  -49.16563576  -11.06563576  -79.46563576   64.53436424  133.23436424
  134.53436424  -41.46563576   72.53436424   -1.16563576   77.33436424
    6.73436424   15.63436424   -4.96563576   34.73436424]
Offset -36.865635755887595
Test accuracy 67.64705882352942% (230 of 340)



### f) With ones as initial parameters over 10 epochs with offset

In [22]:
theta, offset = init_params_with_ones(len(train_features[0]))
theta, offset = train_perceptron_with_offset(theta, offset, train_features, train_target, 10)
acc, correct, test_count = test_perceptron(theta, offset, test_features, test_target)
print(f'Results after 10 epochs:\n'
      f'Theta {theta}\nOffset {offset}\n'
      f'Test accuracy {acc*100}% ({correct} of {test_count})\n')

Results after 10 epochs:
Theta [ 258.  -277.7  558.2  182.6   93.4  -69.7  -27.3 -182.3   36.1  216.8
  199.8  -57.6  142.2    2.1  149.8   -7.2   21.6  -10.9   30.9]
Offset -69.0
Test accuracy 67.64705882352942% (230 of 340)



### g) With ones as initial parameters over 25 epochs with offset

In [23]:
theta, offset = init_params_with_ones(len(train_features[0]))
theta, offset = train_perceptron_with_offset(theta, offset, train_features, train_target, 25)
acc, correct, test_count = test_perceptron(theta, offset, test_features, test_target)
print(f'Results after 25 epochs:\n'
      f'Theta {theta}\nOffset {offset}\n'
      f'Test accuracy {acc*100}% ({correct} of {test_count})\n')

Results after 25 epochs:
Theta [ 233.  -392.3  887.2  271.1 -115.   -48.1  -21.8 -328.8   32.   357.6
  247.   -42.   268.5  -15.4  268.3  109.    62.7  -34.5   18.3]
Offset -158.0
Test accuracy 67.64705882352942% (230 of 340)



### Q: What are your observations based on the subparts d), f) and g) given above [2 points: BONUS]

##TODO ## 

ANS: We can observe that there is not improvement in performance with the increase in epoch. This is a linearly unseparable case due to which perceptron keeps osciliating. We reach optimal solution after 1 epoch and keep oscillating after.

## Q2 Stochastic Gradient with Hinge Loss 
This exercise requires the student to understand the basics of linear classification using stochastic gradient with hinge loss. We will be comparing our functions results with sklearn implementation of hinge loss


Implement Hinge-loss stochastic gradient descent classification from scratch, and compare their answers with scikit learn's implementation of Hinge Loss for sanity check.

In [24]:
# This function should return the hinge loss (empirical risk) for your current theta vector: "theta" is your current theta vector, "xs" is the feature vectors from the training dataset.
#"ys" is the output vector (the vector of "labels") This question worth [6 points]
def hg_loss(theta, offset, xs, ys):
    
    ## TODO ##
    ls = 1-((np.dot(xs,theta)+offset)*ys) 
    return sum([i if i>0 else 0 for i in ls ])/len(xs) 
    ##########

In [25]:
#Through this function, you need to write from scratch of a stochastic gradient (using hinge-loss function) training algorithms with offset.
#for the input: "theta" is the initial theta vector, "xs" is our feature vectors from the training dataset.
#"ys" is the output vector (the vector of "labels"), "epochs" is the number of times your algorithm run through the whole training dataset.
#This question worth [16 points]

theta, offset = init_params_with_zeroes(len(train_features[0]))
def train_SGD_with_hinge_loss(theta, offset, xs, ys, epochs):
    ### TODO ##
    k = 0
    best_param = theta.copy() 
    best_offset = offset 
    best_loss = hg_loss(theta, offset, xs, ys) 
    order = [i for i in range(0,len(xs))]
    random.Random(1).shuffle(order) 
    while epochs>0:
        lr = 1/(k+1) 
        for n in order:
            i,j = xs[n], ys[n]
            if j*(np.dot(i, theta) + offset)<=1: 
                theta += i*j*lr 
                offset += j*lr 
                k+=1
                lr = 1/(k+1)
                loss = hg_loss(theta, offset, xs, ys)
                if loss < best_loss: 
                    best_loss = loss
                    best_param = theta.copy()
                    best_offset = offset
        epochs-=1
            
    print(best_param, best_offset)
    return best_param, best_offset
    ###########

In [26]:
theta, offset = init_params_with_ones(len(train_features[0]))
theta, offset
theta, offset = train_SGD_with_hinge_loss(theta, offset, train_features, train_target, 10)
theta, offset
acc, correct, test_count = test_perceptron(theta, offset, test_features, test_target)
print(f'Results after 10 epochs:\n'
      f'Theta {theta}\n'
      f'Test accuracy {acc*100}% ({correct} of {test_count})\n')

[ 0.14907788 -2.02624254  1.54461817  1.54274004  1.62954787 -0.12351234
  0.67615154 -0.09220192  0.03879626  0.78925535  0.1372067  -0.05736686
  1.25676939  1.18958245  1.45919306  1.68305942  0.68417092  1.24387874
  0.99518122] 0.792644601032122
Results after 10 epochs:
Theta [ 0.14907788 -2.02624254  1.54461817  1.54274004  1.62954787 -0.12351234
  0.67615154 -0.09220192  0.03879626  0.78925535  0.1372067  -0.05736686
  1.25676939  1.18958245  1.45919306  1.68305942  0.68417092  1.24387874
  0.99518122]
Test accuracy 65.58823529411765% (223 of 340)



In [27]:
### Implementing Hinge Loss Using Scikit Learn Package and print the hinge loss [3 points]
from sklearn.metrics import hinge_loss
h_loss = hinge_loss(test_target, np.dot(test_features, theta) + offset) 
h_loss

1.833422873861815

In [28]:
hg_loss(theta, offset, test_features, test_target)

1.8334228738618155

To check if your hinge loss is working correctly

In [29]:
assert 0.00001 > abs(hg_loss(theta, offset, test_features, test_target) - h_loss)